Vidly-Project-iRely/Vidly-Project-iRely/Controllers/MovieRegsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vidly_Project_iRely.Models;

namespace Vidly_Project_iRely.Controllers
{
    public class MovieRegsController : Controller
    {
        private MoviesRentalDbEntities db = new MoviesRentalDbEntities();

        // GET: MovieRegs
        public ActionResult Index()
        {
            return View(db.movieRegs.ToList());
        }

        // GET: MovieRegs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movieReg movieReg = db.movieRegs.Find(id);
            if (movieReg == null)
            {
                return HttpNotFound();
            }
            return View(movieReg);
        }

        // GET: MovieRegs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MovieRegs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,movieno,movietitle,genre,available")] movieReg movieReg)
        {
            if (ModelState.IsValid)
            {
                db.movieRegs.Add(movieReg);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movieReg);
        }

        // GET: MovieRegs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movieReg movieReg = db.movieRegs.Find(id);
            if (movieReg == null)
            {
                return HttpNotFound();
            }
            return View(movieReg);
        }

        // POST: MovieRegs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,movieno,movietitle,genre,available")] movieReg movieReg)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movieReg).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movieReg);
        }

        // GET: MovieRegs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movieReg movieReg = db.movieRegs.Find(id);
            if (movieReg == null)
            {
                return HttpNotFound();
            }
            return View(movieReg);
        }

        // POST: MovieRegs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            movieReg movieReg = db.movieRegs.Find(id);
            db.movieRegs.Remove(movieReg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vidly-Project-iRely/Vidly-Project-iRely/Controllers/returnmovieController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly_Project_iRely.Models;

namespace Vidly_Project_iRely.Controllers
{
    public class returnmovieController : Controller
    {

        MoviesRentalDbEntities db = new MoviesRentalDbEntities();

       

        // GET: returnmovie
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save(returnmovie returnmov)
        {

            if (ModelState.IsValid)
            {
                db.returnmovies.Add(returnmov);

                var movie = db.movieRegs.SingleOrDefault(e => e.movieno == returnmov.movieno);

                if (movie == null)
                
                    return HttpNotFound("Movie Number not Found");
                    movie.available = "Return";
                    db.Entry(movie).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                
            }
            return View(returnmov);
        }

        [HttpPost]
        public ActionResult Getid(String movieno)
        {
            var movienum = (from s in db.rents
                            where s.movieid == movieno
                            select new
                            {
                                StartDate = s.startdate,
                                EndDate = s.enddate,
                                Customerid = s.customerid,
                                Movieno = s.movieid,
                                Fee = s.fee,
                                ElapsedDays = SqlFunctions.DateDiff("day", s.enddate, DateTime.Now)


                            }).ToArray();
            return Json(movienum,JsonRequestBehavior.AllowGet);
        }
    }
}

Vidly-Project-iRely/Vidly-Project-iRely/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/myStyle.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit&family=Roboto:wght@300;500&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    @*@Styles.Render("~/Content/css/myStyle.css")*@
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <style>
      
        .navbar-nav .nav-link{
            color: black;
            font-size: 20px;
            font-family: 'Kanit', sans-serif;
        }

        .navbar-brand {
            color: black;
        }

            .navbar-brand:hover {
                color: rgba(0, 0, 0, 0.5);
            }

            .navbar-brand:hover {
                color: rgba(0, 0, 0, 0.5);
            }

        .nav-link:hover {
            color: rgba(0, 0, 0, 0.5);
            text-decoration: none;
        }
        .navbar-brand {
            font-size: 24px;
            font-family: 'Kanit', sans-serif;

        }
        .foot {
          width: 100%;
        }

    </style>

    <nav class="navbar navbar-expand-lg navbar-dark bg-light fixed-top">
        <div class="container">
            @Html.ActionLink("Vidly-iRely", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler " style="background:rgba(0, 0, 0, 0.9);" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav m-auto justify-content-center text-center">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Movie Register", "Index", "MovieRegs", new { area = "" }, new { @class = "nav-link" })

                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Customer", "Index", "Customer", new { area = "" }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item ">
                        @Html.ActionLink("Rent", "Index", "Rent", new { area = "" }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item ">
                        @Html.ActionLink("Return", "Index", "returnmovie", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
                <form class="d-flex align-items-center justify-content-center">
                    <button class="btn btn-primary my-2 my-sm-0" type="submit">Login</button>
                </form>
            </div>
        </div>
    </nav>



    <div class="container body-content py-5 my-5" id="bot">
        @RenderBody()
        <hr />
     
            <footer class="text-dark foot container " style="font-size: 24px; text-align: center; max-width: none;">
                <p>&copy; @DateTime.Now.Year - Vidly-iRely - <a href="#" class="text-dark">Privacy Policy</a></p>
            </footer>
        


    </div>



    @Scripts.Render("~/bundles/jquery")
    @*/@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include Bootstrap toast plugin -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>